@startuml
actor client
participant "Guichet Automatique" as ATM
participant "Système Bancaire" as Bank

client -> ATM : insere la carte
ATM -> Client : demande code (password)pin
client -> ATM : Entrez code (password)pin
ATM -> Bank : Verifie le code (password)pin
Bank -> ATM : Code (password)pin correct
ATM -> Client : demande montant
client -> ATM : Entrez le montant
ATM -> Bank : Verifie le solde
alt Solde suffisant
    Bank -> ATM : Solde disponible
    ATM -> client : Distribue les billets
    ATM -> client : Imprime le reçu
else Solde insuffisant
    Bank -> ATM : Solde insuffisant
    ATM -> client : Message d'erreur
end
@enduml